/-
Copyright (c) 2026 Elman-Proofs Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.

# Extract trust-gate theorems to structured JSON

Walks the elaborated environment after importing `ElmanProofs.PaperCore`,
keeps only declarations whose source module lives in the trust-gate import
closure, and writes a JSON document to `paper/data/lean-trust-gate-theorems.json`
containing for each declaration: name, kind, file, line, pretty-printed
signature, pretty-printed value/proof body, doc-string, and the list of
constants the value transitively mentions (one level).

Invocation (from `formal/lean/`):

    lake env lean scripts/extract_theorems.lean

The `#eval` block at the bottom does the work; `lake env lean` elaborates the
file and the `#eval` performs the extraction and write. The wrapper script
`scripts/extract_theorems.sh` is the standard entry point because it also pins
the trust-gate commit hash and the extraction timestamp into the output.

Read-only: no Lean source file under `ElmanProofs/` is modified.
-/

import ElmanProofs.PaperCore
import Lean

open Lean Elab Meta

namespace ExtractTheorems

/-- Modules in the trust-gate import closure of `ElmanProofs.PaperCore`.
Derived from `lake env lean --src-deps ElmanProofs/PaperCore.lean`. -/
def trustGateModules : Array Name := #[
  `ElmanProofs.PaperCore,
  `ElmanProofs.Architectures.M2RNNComparison,
  `ElmanProofs.Architectures.MultiStepSeparation,
  `ElmanProofs.Architectures.OnlineMemory,
  `ElmanProofs.Architectures.RecurrentResourceFormalism,
  `ElmanProofs.Architectures.S5Inseparability,
  `ElmanProofs.Expressivity.E88ExceedsE1HCapacity,
  `ElmanProofs.Expressivity.NDMRealizesS5,
  `ElmanProofs.Expressivity.S5NDMRealization,
  `ElmanProofs.Expressivity.S5Tracker,
  `ElmanProofs.Expressivity.S5Witness
]

/-- Relative source path (under `formal/lean/`) for a module name. -/
def moduleToPath (m : Name) : String :=
  m.toString.map (fun c => if c == '.' then '/' else c) ++ ".lean"

def kindOf : ConstantInfo → String
  | .axiomInfo _ => "axiom"
  | .defnInfo _ => "def"
  | .thmInfo _ => "theorem"
  | .opaqueInfo _ => "opaque"
  | .quotInfo _ => "quot"
  | .inductInfo _ => "inductive"
  | .ctorInfo _ => "ctor"
  | .recInfo _ => "rec"

def constInfoValue? : ConstantInfo → Option Expr
  | .defnInfo v => some v.value
  | .thmInfo v => some v.value
  | .opaqueInfo v => some v.value
  | _ => none

/-- True if `n` was introduced internally by elaboration (hygiene fragments,
compiler stage names, etc.). Note: `Name.isInternal` would also strip
`_private` names, but those correspond to genuine `private theorem` source
declarations — we keep them and let `findDeclarationRanges?` filter them. -/
def isInternal (n : Name) : Bool :=
  n.hasMacroScopes
  || (n.toString.endsWith "._sunfold")
  || (n.toString.endsWith "._cstage1")
  || (n.toString.endsWith "._cstage2")

/-- Pretty-print an expression at 100 columns. -/
def fmtExpr (e : Expr) : MetaM String := do
  let fmt ← ppExpr e
  return fmt.pretty 100

/-- Extraction entry for a single declaration. -/
structure DeclEntry where
  name : String
  kind : String
  module : String
  file : String
  line : Nat
  endLine : Nat
  signature : String
  proofBody : String
  sourceText : String
  dependsOn : Array String
  doc : String
  autoGenerated : Bool
  deriving Inhabited

def DeclEntry.toJson (e : DeclEntry) : Json :=
  Json.mkObj [
    ("name", e.name),
    ("kind", e.kind),
    ("module", e.module),
    ("file", e.file),
    ("line", Json.num (JsonNumber.fromNat e.line)),
    ("end_line", Json.num (JsonNumber.fromNat e.endLine)),
    ("signature", e.signature),
    ("proof_body", e.proofBody),
    ("source_text", e.sourceText),
    ("depends_on", Json.arr (e.dependsOn.map Json.str)),
    ("doc", e.doc),
    ("auto_generated", Json.bool e.autoGenerated)
  ]

/-- Suffix list of names that Lean's elaborator generates from
`inductive`/`structure`/equation-compiler declarations. These inherit the
parent declaration's source range, so we flag them but keep them; the
renderer can filter on the `auto_generated` field. -/
def auxSuffixes : List String := [
  ".rec", ".recOn", ".casesOn", ".brecOn", ".below", ".ibelow",
  ".noConfusion", ".noConfusionType",
  ".ctorIdx", ".ctorElim", ".ctorElimType", ".toCtorIdx",
  ".injEq", ".inj", ".sizeOf_spec",
  ".ofNat_ctorIdx", ".ofNat",
  ".eq_def", ".repr"
]

/-- True if the last segment of the name is `eq_N` or `match_N` for some N
(equation-compiler aux declarations). -/
def hasNumericAuxSuffix (n : Name) : Bool :=
  match n with
  | .str _ s =>
    if s.startsWith "eq_" then
      (s.drop 3).toList.all Char.isDigit && (s.length > 3)
    else if s.startsWith "match_" then
      (s.drop 6).toList.all Char.isDigit && (s.length > 6)
    else
      false
  | _ => false

def isAuxName (n : Name) : Bool :=
  let s := n.toString
  hasNumericAuxSuffix n || auxSuffixes.any (fun suf => s.endsWith suf)

/-- Read bytes of a file between two `Position`s (1-indexed lines, 0-indexed
columns). Returns the empty string on any I/O failure. -/
def readSourceRange (path : System.FilePath) (startLine endLine : Nat) :
    IO String := do
  try
    let contents ← IO.FS.readFile path
    let lines := contents.splitOn "\n"
    if startLine == 0 then return ""
    -- 1-indexed -> 0-indexed
    let startIdx := startLine - 1
    let endIdx := if endLine ≥ startLine then endLine - 1 else startIdx
    let slice := (lines.drop startIdx).take (endIdx - startIdx + 1)
    return String.intercalate "\n" slice
  catch _ => return ""

/-- Build a `DeclEntry` for one declaration. -/
def extractDecl (name : Name) (info : ConstantInfo) (modName : Name)
    (srcRoot : System.FilePath) : MetaM (Option DeclEntry) := do
  if isInternal name then return none
  let env ← getEnv
  let kind := kindOf info
  let signature ← fmtExpr info.type
  let proofBody ← match constInfoValue? info with
    | some v => fmtExpr v
    | none => pure ""
  let deps :=
    match constInfoValue? info with
    | some v => v.getUsedConstants
    | none => info.type.getUsedConstants
  let depList : Array String :=
    (deps.filter (· ≠ name)).map Name.toString
  let doc := (← findDocString? env name).getD ""
  let (line, endLine) ← match (← findDeclarationRanges? name) with
    | some r => pure (r.range.pos.line, r.range.endPos.line)
    | none => pure (0, 0)
  -- Drop declarations with no source range; they are pure kernel auxiliaries.
  if line == 0 then return none
  let file := moduleToPath modName
  let sourceText ← liftM (readSourceRange (srcRoot / file) line endLine)
  return some {
    name := name.toString,
    kind := kind,
    module := modName.toString,
    file := file,
    line := line,
    endLine := endLine,
    signature := signature,
    proofBody := proofBody,
    sourceText := sourceText,
    dependsOn := depList,
    doc := doc,
    autoGenerated := isAuxName name
  }

def runExtraction (srcRoot : System.FilePath) : MetaM (Array DeclEntry) := do
  let env ← getEnv
  let moduleSet : Std.HashSet Name :=
    trustGateModules.foldl (init := ∅) fun acc m => acc.insert m
  let mut entries : Array DeclEntry := #[]
  for (name, info) in env.constants.toList do
    let some modIdx := env.getModuleIdxFor? name | continue
    let modName := env.allImportedModuleNames[modIdx.toNat]!
    unless moduleSet.contains modName do continue
    if let some entry ← extractDecl name info modName srcRoot then
      entries := entries.push entry
  let sorted := entries.qsort (fun a b =>
    if a.file ≠ b.file then a.file < b.file
    else if a.line ≠ b.line then a.line < b.line
    else a.name < b.name)
  return sorted

/-- Write the extracted JSON array to the given output path. -/
def runAndWrite (outPath : System.FilePath) (srcRoot : System.FilePath) :
    MetaM Unit := do
  let entries ← runExtraction srcRoot
  let arr := Json.arr (entries.map DeclEntry.toJson)
  IO.FS.writeFile outPath arr.pretty
  IO.println s!"extract_theorems: wrote {entries.size} declarations to {outPath}"

end ExtractTheorems

-- Default output path is read from the `EXTRACT_OUTPUT` env var, or
-- `../../paper/data/lean-trust-gate-theorems.json` relative to `formal/lean/`.
-- Source-text reads also need a root directory: defaults to `.` (i.e. the
-- `formal/lean/` invocation directory).
#eval show MetaM Unit from do
  let envOut ← IO.getEnv "EXTRACT_OUTPUT"
  let envRoot ← IO.getEnv "EXTRACT_SRC_ROOT"
  let out : System.FilePath :=
    envOut.getD "../../paper/data/lean-trust-gate-theorems.json"
  let srcRoot : System.FilePath := envRoot.getD "."
  ExtractTheorems.runAndWrite out srcRoot
